### ISSUE TITLE
Static data source - link to image

### ISSUE THREAD

**Issue by rafal-123** [VolkovLabs/volkovlabs-static-datasource#32]
It is possible to add an image to Postgres database and then show it Grafana UI from plugin. But I wonder if you could add functionality to show an image in Grafana based on a URL added to the static data source.

**Comment by mikhail-vl** [comment]
You don't need to use the data source to display images using a URL. You can display it directly using the `Text` or `Dynamic Text` panels using markdown or HTML.

**Comment by rafal-123** [comment]
@mikhail-vl can you share example in your docs or here how to perform it?
