### ISSUE TITLE
Allow to generate and fetch values with JavaScript

### ISSUE THREAD

**Issue by mikhail-vl** [VolkovLabs/volkovlabs-static-datasource#36]
Query Editor should allow selection between
1. Manual Values Editor
2. New Code Editor to return data frames using JavaScript Code.

Fields definitions should be set for both in Fields Editor. No changes there.

The function executed using Custom Code should return (model: DataFrameModel) similar to ValuesEditor.

**Comment by nicolaerosia** [comment]
This would be great - maybe also a javascript transform which would allow to manipulate any datasource fetched data

**Comment by mikhail-vl** [comment]
@nicolaerosia I am thinking of making a custom transformation with Javascript as well.
