### ISSUE TITLE
Is it possible to return the current time, for use as an annotation?

### ISSUE THREAD

**Issue by dresco** [VolkovLabs/volkovlabs-static-datasource#38]
Hi, just wondering whether this plugin is able to return the current time, rather than a manually entered time?

My use case is wanting an annotation line to reflect the current time within a time series chart panel. Have so far failed to achieve this with my Prometheus data source..

Anyway, just a thought - thanks!

**Comment by mikhail-vl** [comment]
@dresco We are planning to add a JavaScript Code in the upcoming version and it will be possible.

  If you have a data source like Postgres, it's pretty simple to do.

**Comment by dresco** [comment]
> @dresco We are planning to add a JavaScript Code in the upcoming version and it will be possible.

That's good news, thanks.

> If you have a data source like Postgres, it's pretty simple to do.

Unfortunately I don't have any SQL on this box, am migrating from InfluxDB (1.x) to VictoriaMetrics/Prometheus time series database. I've seen a couple of posts on using SQLserver and Flux queries to get the system time, but I've not been able to figure out a way with what I have..

**Comment by mikhail-vl** [comment]
Resolves in #44.
