### ISSUE TITLE
Javascript example

### ISSUE THREAD

**Issue by XIIIVI** [VolkovLabs/volkovlabs-static-datasource#50]
Hi,

It is not an issue but a question.
I would like to use the static datassource but not in manual mode but with Javascript.

Even if there is a code snippet, is there any detailed example I can get inspired from ?

Many thanks for your help,

Enjoy your WE !

**Comment by mikhail-vl** [comment]
@XIIIVI Please share if you created something already. We don't have any detailed examples, we did not have time to play with it after the release.

  We will publish a new version of the Static Data Source and will include examples in the blog post.

**Comment by mikhail-vl** [comment]
Example added in the documentation: https://volkovlabs.io/plugins/volkovlabs-static-datasource/panels/business-charts/
