### ISSUE TITLE
Javascript order of execution

### ISSUE THREAD

**Issue by raymondsowden** [VolkovLabs/volkovlabs-static-datasource#68]
Hi,

I have an issue where I am trying to dynamically generate the names and values array from an api, but even though the array gets updated, the script returns no data. Please help!

// create blank jagged array
const values = [[], []];
// this works
//const values = [['Cheese', 'Crisps', 'Pizza', 'Chocolate', 'Self-raising flour', 'Ground almonds'], [2.5, 3, 4, 1.5, 1.5, 3]];

// fetch an example json payload
fetch('https://raw.githubusercontent.com/mdn/dom-examples/main/fetch/fetch-json/products.json')
  .then((response) => response.json())
  .then((data) => {
    for (const product of data.products) {
      // push the values for names and prices onto the array from the response
      values[0].push(product.Name)
      values[1].push(product.Price)
    }
  })
  .catch(console.error)

// print values to the console, should be a jagged array
console.log(values)

// build the frame to return the data to grafana
result = {
  ...frame,
  fields: frame.fields.map((field, i) => ({
    ...field,
    values: values[i]
  }))
}

// let grafana plot the data
return Promise.resolve(result);

**Comment by raymondsowden** [comment]
Promises execute immediately

**Comment by mikhail-vl** [comment]
@raymondsowden Glad you able to resolve the issue.

  Please let us know if there is anything else.
